### ISSUE TITLE
【任务发布】支持toml格式的dadk配置文件

### ISSUE THREAD

**Issue by fslongjin** [DragonOS-Community/DADK#25]
## 需求

由于目前dadk配置文件是json格式的，不方便打注释，并且修改比较麻烦，因此需要增加新版的解析器，把dadk配置文件改为toml格式的，同时兼容已有的json格式的dadk配置文件（如果toml里面加了新的feature,只用考虑toml的兼容性就行了）。但是需要向前兼容已有的json格式的配置文件。

**Comment by fslongjin** [comment]
@YJwu2023

**Comment by Chiichen** [comment]
在做吗，我想把这个功能做上，我不想保留对之前json的兼容性，因为现在文件不多，做迁移不复杂，json可以很容易地转换到toml

**Comment by Chiichen** [comment]
> 这个很简单，因为serde已经集成了相应的功能，只要加一个toml库，就可以直接做一键的序列化和反序列化了。
> 
> 
> 
> 而且要兼容的话，好像也没什么问题，反正是固定的

主要是不想同时存在两种格式的配置文件，看起来怪怪的，反正迁移也没有什么成本

**Comment by fslongjin** [comment]
> > 这个很简单，因为serde已经集成了相应的功能，只要加一个toml库，就可以直接做一键的序列化和反序列化了。
> > 而且要兼容的话，好像也没什么问题，反正是固定的
> 
> 主要是不想同时存在两种格式的配置文件，看起来怪怪的，反正迁移也没有什么成本

这样会存在一个问题，导致我们没法编译旧的版本的dragonos.

前向的兼容性很重要。尤其是我们比如想返回以前版本来测试某个bug是否存在的时候。所以在短时间内还是必须要保持对前面的兼容性的。可以在新版的地方加一个字段，就是标志一下解析器的版本号，那么我们就可以采取不同的策略
