### ISSUE TITLE
【bug】按照原有文档流程创建用户程序编译失败，推测是DADK的原因

### ISSUE THREAD

**Issue by val213** [DragonOS-Community/DADK#54]
![20b5b80ffe08190637d779e1bfdceef](https://github.com/DragonOS-Community/DADK/assets/112376067/da92b50b-2d87-4c99-9e8f-ab9d91b8caea)

![image](https://github.com/DragonOS-Community/DADK/assets/112376067/b5a7382d-80cb-4ddd-8818-a0306b5c9cae)

复现步骤：按照原有文档步骤创建rust用户程序https://docs.dragonos.org/zh-cn/latest/userland/appdev/index.html

**Comment by fslongjin** [comment]
编译配置文件放一下上来，这里输出的是执行你那个编译任务的时候，任务本身的错误。

**Comment by val213** [comment]
> 编译配置文件放一下上来，这里输出的是执行你那个编译任务的时候，任务本身的错误。

在Makefile里指定工具链参数就可以编译了，TOOLCHAIN="+nightly-2023-08-15-x86_64-unknown-linux-gnu"，原本默认是TOOLCHAIN=""。但是为啥之前不需要这一步哈哈
